### PR TITLE
Add file upload progress bar  - #1 .

### PR DESCRIPTION
**Pull request by saif-malik-01**
* Functionality added #1

### CODE REVIEW

**Comment by ahmedashfaq027** [comment]
@saif-malik-01, I like the UI design of how you organized it, But I see that 1gb file upload is throwing some exception.
Can you please recheck that?

**Comment by saif-malik-01** [comment]
Ok, I will check and notify you soon.

**Comment by ahmedashfaq027** [comment]
@saif-malik-01, My bad the DB Url was wrong.
I'm impressed. it works really good. Thanks for your contribution

**Comment by saif-malik-01** [comment]
Thank you :)

**Pull request merged**
